---
    - name: Playbook to install mongoDB
      hosts: db
      tags: db-tag
      tasks:
        - name: Add mongo ppa key
          become: true
          shell:
            cmd: wget -qO - https://www.mongodb.org/static/pgp/server-4.0.asc | apt-key add -
        - name: Add MongoDB repository into sources list
          apt_repository:
            repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
            state: present
        - name: Ansible apt install ca-certificates
          become: true
          apt:
            name: ca-certificates
            state: present
        - name: Ansible apt install apt-transport-https
          become: true
          apt:
            name: apt-transport-https
            state: present
        - name: Ansible apt install mongoDB
          become: true
          apt:
            name: mongodb-org
            state: present

    - name: Playbook to install git
      hosts: app
      tags: app-tag
      tasks:
        - name: Ansible apt install git
          become: true
          apt:
            name: git
            state: present
        - name: Ansible apt install ruby-full
          become: true
          apt:
            name: ruby-full
            state: present
        - name: Ansible apt install ruby-bundler
          become: true
          apt:
            name: ruby-bundler
            state: present

    - name: Playbook to restart puma
      hosts: app
      tags: deploy-tag
      tasks:
        - name: restart puma
          become: true
          systemd:
            name: puma
            state: restarted
